#!/bin/bash

BLUE=0xFF1E6E77
ORANGE=0xFFCC7B6E
PINK=0xFFD7448A
RED=0xFFCE3A5B
GREEN=0xFF638989
WHITE=0xFFFFFFFF
BG1=0xEB1e1e2e
LIGHT_PINK=0xFFD3A3AB
BG_ITEM=0x00000000

sketchybar --bar height=20 \
  margin=15 \
  y_offset=0 \
  padding_left=0 \
  padding_right=0 \
  color=0x00000000
#  blur_radius=0

sketchybar --default updates=when_shown \
  icon.font="Liga SFMono Nerd Font:Normal:14.0" \
  label.font="Liga SFMono Nerd Font:Normal:14.0" \
  label.color=$WHITE \
  background.color=$BG_ITEM \
  y_offset=0

sketchybar --add event aerospace_workspace_change
sketchybar --add event title_change

sketchybar --add item title left \
  --set title \
  label.padding_left=12 \
  label="Title" \
  background.drawing=off \
  icon.padding_left=0 \
  icon.padding_right=0 \
  script="$HOME/.config/sketchybar/scripts/title.sh" \
  update_freq=1 \
  label.max_chars=54 \
  label.color=$WHITE

sketchybar --subscribe title title_change

for sid in $(aerospace list-workspaces --all | sed 's/ *| *//g'); do
  if [[ -n "$sid" ]]; then
    sketchybar --add item aerospace_ws.$sid left \
      --set aerospace_ws.$sid \
      icon=" $sid " \
      icon.font="Liga SFMono Nerd Font:Normal:14.0" \
      icon.color=$PINK \
      icon.padding_left=10 \
      icon.padding_right=10 \
      label.drawing=off \
      background.drawing=off \
      click_script="aerospace focus-workspace '$sid'" \
      script="$HOME/.config/sketchybar/scripts/aerospace.sh $sid"
    sketchybar --subscribe aerospace_ws.$sid aerospace_workspace_change
  fi
done

sketchybar --default \
  icon.padding_left=12 \
  icon.padding_right=4 \
  label.padding_left=4 \
  label.padding_right=12

sketchybar --add item countdown_updater left \
  --set countdown_updater \
  script="$HOME/.config/sketchybar/scripts/countdown.sh" \
  update_freq=60 \
  drawing=off

#sketchybar --add item countdown center \
#  --set countdown \
#  script="$HOME/.config/sketchybar/scripts/countdown.sh" \
#  update_freq=1 \
#  label="Loading Task..." \
#  label.color=$WHITE \
#  icon.padding_left=10 \
#  label.padding_left=5 \
#  label.padding_right=10 \
#  click_script="open -a Obsidian \"/Users/zhijie/Archive/zhijie-ob/Others/Homepage.canvas\"" \
#  background.drawing=off

sketchybar --add item time right \
  --set time \
  icon=󱑎 \
  icon.color=$BLUE \
  label="$(date '+%I:%M %p')" \
  script="$HOME/.config/sketchybar/scripts/time.sh" \
  update_freq=1 \
  background.drawing=off

sketchybar --add item date right \
  --set date \
  icon=󱨰 \
  icon.color=$GREEN \
  label="$(date '+%a %b %d')" \
  script="$HOME/.config/sketchybar/scripts/date.sh" \
  update_freq=10 \
  background.drawing=off

sketchybar --add item title_proxy right \
  --set title_proxy \
  y_offset=100 \
  label="Title" \
  drawing=off

sketchybar --update
sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$(aerospace list-workspaces --focused)

echo "SketchyBar configuration loaded (No right-side backgrounds)."
